language: c
env:
  global:
    - MAKEFLAGS="-j 2"
matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode12.2
      arch: amd64
    - os: osx
      compiler: clang
      osx_image: xcode11.4
      arch: amd64
    - os: osx
      compiler: clang
      osx_image: xcode11.3
      arch: amd64
    - os: osx
      compiler: clang
      osx_image: xcode11.2
      arch: amd64

install:
  - ci/travis-install.sh

script:
  - ci/travis-build.sh
