language: c
env:
  global:
    - MAKEFLAGS="-j 2"
matrix:
  include:
    - os: osx
      compiler: clang # Workaround travis setting CC=["clang", "gcc"]
      osx_image: xcode7.3
    - os: osx
      compiler: clang
      osx_image: xcode8
  exclude:
    - os: osx
      compiler: gcc

install:
  - ci/travis-install.sh

script:
  - ci/travis-build.sh
